name: Compile LaTeX resume
on: push

jobs:
    build_latex:
        name: Building resume
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Compile document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: zhizhin_petr_resume.tex
            - name: Upload PDF as artifact
              uses: actions/upload-artifact@v2
              with:
                  name: resume
                  path: zhizhin_petr_resume.pdf
